package com.dexafree.andfgc.app.utils;

/**
 * Created by Carlos on 26/04/14.
 */
public class Constants {

    public final static boolean DEBUG = true;

    public final String ESTACIO_ABRERA = "AB";
    public final String ESTACIO_ÀGER = "AG";
    public final String ESTACIO_ALCOLETGE = "AC";
    public final String ESTACIO_ALMEDA = "AL";
    public final String ESTACIO_AV_TIBIDABO = "TB";
    public final String ESTACIO_BAIXADOR_DE_VALLVIDRERA = "VL";
    public final String ESTACIO_BALAGUER = "BA";
    public final String ESTACIO_BELLATERRA = "BT";
    public final String ESTACIO_CAN_PARELLADA = "CP";
    public final String ESTACIO_CAN_ROS = "CR";
    public final String ESTACIO_CAPELLADES = "CA";
    public final String ESTACIO_CASTELLBELL_I_EL_VILAR = "CB";
    public final String ESTACIO_CELLERS_LLIMIANA = "CE";
    public final String ESTACIO_COLÒNIA_GÜELL = "CG";
    public final String ESTACIO_CORNELLÀ_RIERA = "CO";
    public final String ESTACIO_EL_PALAU = "PL";
    public final String ESTACIO_EL_PUTXET = "EP";
    public final String ESTACIO_EUROPA_FIRA = "EU";
    public final String ESTACIO_GERB = "GE";
    public final String ESTACIO_GORNAL = "GO";
    public final String ESTACIO_GRÀCIA = "GR";
    public final String ESTACIO_GUÀRDIA_DE_TREMP = "GT";
    public final String ESTACIO_HOSPITAL_GENERAL = "HG";
    public final String ESTACIO_IGUALADA = "IG";
    public final String ESTACIO_ILDEFONS_CERDÀ = "IC";
    public final String ESTACIO_LA_BEGUDA = "BE";
    public final String ESTACIO_LA_BONANOVA = "BN";
    public final String ESTACIO_LA_FLORESTA = "LF";
    public final String ESTACIO_LA_POBLA_DE_CLARAMUNT = "PO";
    public final String ESTACIO_LA_POBLA_DE_SEGUR = "PS";
    public final String ESTACIO_LES_FONTS = "FN";
    public final String ESTACIO_LES_PLANES = "LP";
    public final String ESTACIO_LES_TRES_TORRES = "TT";
    public final String ESTACIO_L_HOSPITALET_AV_CARRILET = "LH";
    public final String ESTACIO_LLEIDA_PIRINEUS = "LL";
    public final String ESTACIO_MAGÒRIA_LA_CAMPANA = "MG";
    public final String ESTACIO_MANRESA_ALTA = "MA";
    public final String ESTACIO_MANRESA_BAIXADOR = "MB";
    public final String ESTACIO_MANRESA_VILADORDIS = "VI";
    public final String ESTACIO_MARTORELL_CENTRAL = "MC";
    public final String ESTACIO_MARTORELL_ENLLAÇ = "ME";
    public final String ESTACIO_MARTORELL_VILA = "MV";
    public final String ESTACIO_MASQUEFA = "MQ";
    public final String ESTACIO_MIRA_SOL = "MS";
    public final String ESTACIO_MOLÍ_NOU_CIUTAT_COOPERATIVA = "ML";
    public final String ESTACIO_MONISTROL_DE_MONTSERRAT = "MO";
    public final String ESTACIO_MONISTROL_VILA = "MI";
    public final String ESTACIO_MONTSERRAT = "MT";
    public final String ESTACIO_MONTSERRAT_AERI = "AE";
    public final String ESTACIO_MUNTANER = "MN";
    public final String ESTACIO_OLESA_DE_MONTSERRAT = "OL";
    public final String ESTACIO_PÀDUA = "PD";
    public final String ESTACIO_PALAU_DE_NOGUERA_TALARN = "PN";
    public final String ESTACIO_PALLEJÀ = "PA";
    public final String ESTACIO_PEU_DEL_FUNICULAR = "PF";
    public final String ESTACIO_PIERA = "PI";
    public final String ESTACIO_PL_CATALUNYA = "PC";
    public final String ESTACIO_PL_ESPANYA = "PE";
    public final String ESTACIO_PL_MOLINA = "PM";
    public final String ESTACIO_PROVENÇA = "PR";
    public final String ESTACIO_QUATRE_CAMINS = "QC";
    public final String ESTACIO_REINA_ELISENDA = "RE";
    public final String ESTACIO_RUBÍ = "RB";
    public final String ESTACIO_SABADELL_ESTACIÓ = "SB";
    public final String ESTACIO_SABADELL_RAMBLA = "RA";
    public final String ESTACIO_SALÀS_DE_PALLARS = "SS";
    public final String ESTACIO_SANT_ANDREU_DE_LA_BARCA = "SA";
    public final String ESTACIO_SANT_BOI = "BO";
    public final String ESTACIO_SANT_CUGAT = "SC";
    public final String ESTACIO_SANT_ESTEVE_SESROVIRES = "SE";
    public final String ESTACIO_SANT_GERVASI = "SG";
    public final String ESTACIO_SANT_JOAN = "SJ";
    public final String ESTACIO_SANT_JOSEP = "SP";
    public final String ESTACIO_SANT_LLORENÇ_DE_MONTGAI = "SM";
    public final String ESTACIO_SANT_QUIRZE = "SQ";
    public final String ESTACIO_SANT_VICENÇ_CASTELLGALÍ = "SV";
    public final String ESTACIO_SANT_VICENÇ_DELS_HORTS = "VH";
    public final String ESTACIO_SANTA_COLOMA_DE_CERVELLÓ = "CL";
    public final String ESTACIO_SANTA_LINYA = "SL";
    public final String ESTACIO_SARRIÀ = "SR";
    public final String ESTACIO_TÉRMENS = "TE";
    public final String ESTACIO_TERRASSA_RAMBLA = "TR";
    public final String ESTACIO_TREMP = "TP";
    public final String ESTACIO_UNIVERSITAT_AUTÒNOMA = "UN";
    public final String ESTACIO_VALLBONA_D_ANOIA = "VA";
    public final String ESTACIO_VALLDOREIX = "VD";
    public final String ESTACIO_VALLFOGONA_DE_BALAGUER = "VF";
    public final String ESTACIO_VALLVIDRERA_INFERIOR = "VR";
    public final String ESTACIO_VALLVIDRERA_SUPERIOR = "SU";
    public final String ESTACIO_VILANOVA_DE_LA_BARCA = "VB";
    public final String ESTACIO_VILANOVA_DE_LA_SAL = "VS";
    public final String ESTACIO_VILANOVA_DEL_CAMÍ = "VN";
    public final String ESTACIO_VOLPELLERES = "VO";

}
